### PR TITLE
Change max_property_value value string

### PR DESCRIPTION
**Pull request by randstr**
Some higher-level language EditorConfig libraries with multiple return
types might interpret the string "0000...1" as the type "number" and
value "1" (e.g: Lua).

When printed the result will be "1" and not "000...1" and the test fails.

Because the type of the return value is not the purpose of this test,
just the string length, change the string used to a value that should
never be interpreted as a number and is still suitable for the
max_property_value test.

### CODE REVIEW

**Comment by xuhdev** [comment]
OK... do you think we should add another one testing those zeros?

**Comment by randstr** [comment]
> OK... do you think we should add another one testing those zeros?
In my opinion no, it should be left to the implementation how to interpret the string "000000001". Lua is returning the number 1, which I think is correct but would be awkward to implement in the C library.

I cannot picture a situation where leading zeros should be meaningful.

**Comment by xuhdev** [comment]
@randstr The core library should deliver as much as what was written in the `.editorconfig` files, and left the interpretation to (customized) features that editor plugins support. Does this make sense?

**Comment by randstr** [comment]
It does make sense, as stated, and I agree. Lua will return every value as a string then. It's no problem. Thanks.

**Pull request closed without merging**
