### PR TITLE
Fix octothorpe comment tests

### PR DESCRIPTION
**Pull request by jedmao**

### CODE REVIEW

**Comment by xuhdev** [comment]
What should we do with this PR? Should we keep tests for both semicolon and octothorpe?

**Comment by xuhdev** [comment]
ping @jedmao Shall we move on :smile: ? cc @rakus

**Comment by jedmao** [comment]
1. To answer your first question, there are already tests for both semicolon and octothorpe. Yes I think we should keep both.
1. Still waiting on PR approval before merge.

**Comment by xuhdev** [comment]
LGTM

**Pull request merged**
