### PR TITLE
Spec property name and value limits

### PR DESCRIPTION
**Pull request by josh**
*(Current patch for purposes of discussion)*

I'm curious what people think about spec'ing some limits for things like maximum property name and value sizes.

The C implementation has defined max lengths of 500 for section and properties.

https://github.com/editorconfig/editorconfig-core-c/blob/ab5a28de6420188a128571fd579aebe6e49e0abd/src/lib/ini.h#L80-L81

I realize this maybe too implementation specific. But I think its interesting because we could have well defined behavior for what happens when the limits are exceeded.

* These properties could simply be ignored if they exceed the max lengths
* Or, these properties could be truncated to fit the max length

Any thoughts? Has this already been discussed in the past?

Thanks.

### CODE REVIEW

**Comment by treyhunner** [comment]
We have not discussed this before.  It seems reasonable to ignore these properties when the maximum length is exceeded.

We could write a test to ignore these properties past the maximum value and then update each of the core libraries to make them behave consistently.  I can't imagine a property needing more than 500 characters.  Any reason to change that value or should we use that as the maximum?

**Comment by josh** [comment]
> I can't imagine a property needing more than 500 characters. Any reason to change that value or should we use that as the maximum?

It seems like the property name itself could be much shorter. Maybe something like:

* Max property name 50c
* Max property value 255c

**Comment by xuhdev** [comment]
Yes, we should ignore long names. Perhaps also print a standardized warning message to stderr?

**Comment by xuhdev** [comment]
I agree the limit set by @josh. We (and other people) would probably have no chance to define a property longer than 50c.

**Comment by treyhunner** [comment]
Those two limits sound reasonable to me also.

**Comment by josh** [comment]
Cool.

Pushed up some changes requiring names <= 50c and values <= 255c.

**Comment by josh** [comment]
I may propose similar behavior for section names as well. Though there seems to be some previous discussions for long paths in section names https://github.com/editorconfig/editorconfig/issues/147.

**Comment by xuhdev** [comment]
@josh section names may be much longer. It maybe never long enough for machine generated code (very long and deep directory). 

The max path length on different platforms:

- [Linux ext4 supports 4096](https://stackoverflow.com/questions/9449241/where-is-path-max-defined-in-linux)
- [Windows NTFS supports 32767 chars, but EditorConfig only supports the formats the 260 char max format](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)
- OS X HFS Plus: we have no idea.

I would say setting the limit to 4096 + a small number (say 256) should be enough to deal most cases.

**Comment by josh** [comment]
@xuhdev yeah, I can explore that. Is there any other specific feedback for this PR for property name/values? Should this be merged first or should I try to include the section name limits here as well? Thanks!

**Comment by treyhunner** [comment]
I finally got around to merging this.  Sorry for the delay.  Thank you @josh!

**Comment by josh** [comment]
Thanks!

**Comment by Mpdreamz** [comment]
@editorconfig/board-member  should these limits be documented somewhere ?

I'm updating the .NET core implementation to the latest tests and noticed I don't enforce these limits.

https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017

Has quite a few domain specific properties exceeding `50` characters e.g `dotnet_style_predefined_type_for_locals_parameters_members`.

**Comment by ffes** [comment]
I don't have a strong opinion on this, but I don't see why we should limit the size is a property or a value. If there is no technical reason to limit, why do it?

This issue was opened in 2015, the project and its use and adoption has changes since then. The use of EditorConfig has become so ubiquitous.

**Comment by xuhdev** [comment]
I don't oppose either. What about other implementations? Do they impose a limit?

**Comment by florianb** [comment]
@josh - thanks for your work!

:+1: for documenting the limits. If there is one platform forcing limits the limits should be standard-wide.

**Comment by jedmao** [comment]
I agree with @ffes that if there's no technical reason to enforce a limit, then why do it?

If all devs on a particular team are using an OS that supports super long path lengths, then any smaller limits would be artificial for them. It shouldn't matter to them if some other OS has a limit that doesn't concern them.

Conversely, if there is a technical reason that a long name would cause some OS-specific crash, then let the OS crash? The error message would most likely be more accurate, pointing out whatever technical limitation the OS has.

I'm currently trying to add these limits to a [Pest grammar](https://pest.rs/). It's totally fine with the smaller limits, but crashes with the 4096 one (i.e., if I try to add `{1,4096}` to the regex that captures the section name).

Would love to revert limits if we can't defend a good reason to keep them. It both complicates the spec and the implementations.

**Pull request merged**
